name: build to page

on:
    push:
        branches: ['main']

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Get current date
              id: date
              run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

            - name: set Node
              uses: actions/setup-node@v3

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      crustio/tonbags-tgbot:latest
                      crustio/tonbags-tgbot:${{env.date}}
